//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public string GroupId { get; set; }
        public string SysFunctionsID { get; set; }
        public Nullable<bool> AD { get; set; }
        public Nullable<bool> De { get; set; }
        public Nullable<bool> Up { get; set; }
        public Nullable<bool> Query { get; set; }
        public Nullable<bool> Ex { get; set; }
        public Nullable<bool> Im { get; set; }
    }
}
