//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelSetting
    {
        public string Type { get; set; }
        public string CustomerCode { get; set; }
        public string VKORG { get; set; }
        public string VTWEG { get; set; }
        public string SPART { get; set; }
        public string CustomerName1 { get; set; }
        public string CustomerName2 { get; set; }
        public string EnterpriseGroup { get; set; }
        public string Sorg { get; set; }
        public string SPEC { get; set; }
        public string DC { get; set; }
        public string Qty { get; set; }
        public string CustomerPartNo { get; set; }
        public string ItemDescreption1 { get; set; }
        public string ItemDescreption2 { get; set; }
        public string LN { get; set; }
        public string PurchasOrder { get; set; }
        public string LCP { get; set; }
        public string MSLLevel { get; set; }
        public string DC1 { get; set; }
        public string DC2 { get; set; }
        public string DC3 { get; set; }
        public string VC { get; set; }
        public string CustomerVer { get; set; }
        public string Warranty { get; set; }
        public string ItemName { get; set; }
        public string MachineType { get; set; }
        public string ItemNo { get; set; }
        public string customerItemNo { get; set; }
        public string LotNo { get; set; }
        public string Rev { get; set; }
        public string Weight1 { get; set; }
        public string Weight2 { get; set; }
        public string Weight3 { get; set; }
        public string CartonStatus { get; set; }
        public string CartonSeq { get; set; }
        public string OriginalVer { get; set; }
        public string Ary { get; set; }
        public string AryInitialCycle { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Operator { get; set; }
        public string Season1 { get; set; }
        public string Season2 { get; set; }
        public string Season3 { get; set; }
        public string CurrentSeason1 { get; set; }
        public string CurrentSeason2 { get; set; }
        public string CurrentSeason3 { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string day { get; set; }
        public string NextLabel { get; set; }
        public string INV { get; set; }
        public string ZoneCode { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public string Other3 { get; set; }
        public string Other4 { get; set; }
        public string Other5 { get; set; }

        public string DocEntry { get; set; }
    }
}
