//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrtData
    {
        public string DocEntry { get; set; }
        public string PrinterName { get; set; }
        public string PrinterIP { get; set; }
        public string CustomerCode { get; set; }
        public string SPEC { get; set; }
        public string VKORG { get; set; }
        public string VTWEG { get; set; }
        public string SPART { get; set; }
        public string LabelType { get; set; }
        public string LabelData { get; set; }
        public string OPDate { get; set; }
        public string OPDateStart { get; set; }
        public string OPDateEnd { get; set; }
        public string PrinterYN { get; set; }
        public Nullable<int> PrintQty { get; set; }
    }
}
