//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeqProcess
    {
        public string CustomerCode { get; set; }
        public string VKORG { get; set; }
        public string VTWEG { get; set; }
        public string SPART { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public Nullable<System.DateTime> InitialTime { get; set; }
        public string Ary { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Opreator { get; set; }
    }
}
